name: Madison Metro Sim - CQA

on: [ push ]

jobs:
  cqa:
    name: CQA

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install required packages
        run: |
          pip install -r requirements.txt

      - name: Install CQA checkers
        run: |
          pip install pylint pydocstyle

      - name: pydocstyle checks (metro sim)
        run: |
          pydocstyle msnmetrosim --count

      - name: pylint checks (metro sim)
        run: |
          pylint msnmetrosim
